config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  resources :tweets
  resources :roles
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: "tweets#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    def initialize(user)
    if user.nil?
        can :read,[Tweet]
    elsif user.role? "admin"
        #can :manage,[Tweet]
        # can []
        can [:read,:update,:destroy],Tweet
    elsif user.role? "non-admin"
        can [:read,:create,:update,:destroy],Tweet        
    end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  belongs_to :role

 

  def role?(role)
  	puts "Role::#{role}"
    self.role.title == role
   end 

  def role_admin
  	#raise self.role.inspect
    if self.role.title == 'admin'
    	puts "inside if "
    self.errors.add(:base, "Not authorized to Register")
     return false
    end
  end       

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

  before_action :authenticate_user!
  

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do 
    redirect_to root_path, notice: "Unauthorized Access"
  end

  private
  def after_sign_out_path_for(resource_or_scope)
     new_user_session_path
  end

  protected
  
  def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up) do |user_params|
	    user_params.permit({ keys: [] }, :role_id,:email, :password, :password_confirmation,:username)
	  end
	end  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def role_params
      params.require(:role).permit(:title, :description)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [ :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    render json: @tweet ,status: :ok  #{message:" Post created successfully!"},status: :ok 
    #respond_to do |format|
     # puts format.inspect
      #format.html  @tweet
      #format.json {render json: @tweet}
    #end
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
    # authorize! :myroom,Tweet.new
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        #format.html { redirect_to tweets_path, notice: 'Tweet was successfully created.' }
        format.json { render json:@tweet, status: :created }
      else
        #format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      puts format.inspect
      if @tweet.update(tweet_params)
        #format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        #format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    render json: {message:"Deleted successfully"} ,status: :ok
    # respond_to do |format|
      # format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      #format.json { render json: {}}
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestCode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Tweet Management</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              Welcome <%= current_user.username %>
              <li> <%= link_to "AccountSettings", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path ,method: :delete%></li>
              <% else %>
              <li><%= link_to "Login", new_user_session_path %> </li>
              <li><%= link_to "Register", new_user_registration_path %></li>
              
            <% end %>
           </ul>
         </div>
      </div>
    </nav>
    <div class= "container-fluid">
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <%= yield %>
    </div>  
  </body>
</html>

<%# if user_signed_in? %>
  <!-- Welcome <%#= current_user.username %> -->
   <%#= link_to "AccountSettings",edit_user_registration_path %> 
   <%#= link_to "Logout",destroy_user_session_path, method: :delete %> 
  <%# else %>
  <%#= link_to "Login", new_user_session_path %>  <%#= link_to "Register", new_user_registration_path %>
<%# end %>

app/views/roles/_form.html.erb
<%= form_for(role) do |f| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.title %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @role.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/tweets/_form.html.erb
<div class="col-md-10 col-md-offset-1">
  <%= form_for(tweet) do |f| %>
    <% if tweet.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

        <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_field :message ,class:"form-control"%>
    </div>
   
   <%#= tweet.user.role.title%>
    <!-- <div class="form-group">
      <%#= f.label :user_id %>
      <%#= f.number_field :user_id ,class:"form-control"%>
    </div> -->

    <div class="form-group" >
      <%= f.submit class:"btn btn-success btn-cons"%>
      <!-- <button id="save", class= "btn btn-success btn-cons" >Save</button> -->
      <%= link_to 'Cancel',tweets_path , class: "btn btn-danger btn-cons" %>
    </div>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class ="container">
  <div class="panel panel-info">
   <div class="panel-heading">Tweets(<%= @tweets.length %>)</div>
    
    <div class="panel-body">
      <table class="table table-bordered">
        <thead >
          <tr>
            <th>Message</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @tweets.each do |tweet| %>
            <tr>
              <td><%= tweet.message %></td>
              <td><%= tweet.user_id %></td>
              <td><%= link_to 'Show', tweet %></td>
              <% if tweet.user_id == current_user.id || current_user.role.title == 'admin'%>
                <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
               
              <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% else %>
              <td></td>
              <td></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>  

  </div>
  <%= link_to 'New Tweet', new_tweet_path,class:"btn btn-primary btn-cons" %>
</div>  

app/views/tweets/new.html.erb
<div class="col-md-10 col-md-offset-1">
	<div class="panel panel-info">
	  <div class="panel-heading">Add New Tweet</div>
	    <div class="panel-body">
			<%#= render 'form' %>
			<%= render 'form', tweet: @tweet %>
		</div>
	</div>
</div>			

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>